### ISSUE TITLE
Update dockerfile for new dependencies

### ISSUE THREAD

**Issue by gonuke** [cnerg/pyne#1]
Make a Python2 dockerfile that builds all the dependencies for the `pymoab_cleanup` branch

**Comment by kkiesling** [comment]
A new dockerfile has been made and is accessible here: https://github.com/pyne/install_scripts/pull/26

This references branches that should not be used in the final version.

**Comment by kkiesling** [comment]
To build the docker file, clone my branch or copy the file, then run: 
`docker build -f ubuntu_16.04-pymoab.dockerfile -t pyne-pymoab .`

And to run (most basic): `docker run -it pyne-pymoab`

**Comment by gonuke** [comment]
Thanks @kkiesling - I'll close this issue since it looks like it works.
