### ISSUE TITLE
review & update documentation for any references to mesh and determine what needs to be udpated

### ISSUE THREAD

**Issue by gonuke** [cnerg/pyne#13]
There may be various places in the docs that refer to the use of PyNE mesh, and those may need to be updated.

Catalog them in comments here and/or by making additional issues.

... then update those places.

**Comment by zxkjack123** [comment]
The documentation files that contains the keyword `mesh` are listed in: https://docs.google.com/spreadsheets/d/18e8w1PZhQ90E74o4Ok_8L_NkcqL4deDc9je-YVS0opU/edit#gid=376519727, the third sheet "docs_ref_mesh".

**Comment by kkiesling** [comment]
We should also verify that all the example/tutorial notebooks work with our changes in addition to just scouring for the `mesh` keyword.

**Comment by zxkjack123** [comment]
Updates of the documentations related to this issue:
- #42 
- #40 
- #32

**Comment by gonuke** [comment]
We deem this complete - remaining issues are not related to documentation changes, but there are some tutorial notebooks that have errors related to importing `nuc_data.h5`
