### ISSUE TITLE
Add method to delete a tag from a mesh

### ISSUE THREAD

**Issue by gonuke** [cnerg/pyne#26]
While it is possible to delete a tag from a mesh using the pymoab interface, this does not honor the cross-referencing between tags and meshes.

A method should be added to the pyne mesh API to delete a tag and cleanup everything properly.

This is necessary to support the `r2s` script.

**Comment by gonuke** [comment]
I think three steps are required, but not sure about the order:
1. delete the Tag object itself
2. remove from the dictionary of tags on that mesh
3. call delattr() or equivelent

**Comment by gonuke** [comment]
@pshriwise - will this just work with `del myMeshObj.myTag`?

**Comment by gonuke** [comment]
Imagine the following:

```
myMesh = Mesh()
myMesh.tag('myTag',...)
myMesh.myTag[:] = some_data
del myMesh.myTag
```
* I think that this will successfully delete the NativeMeshTag object and all of its data.
* I am not sure if it will delete the attr on the myMesh object.  If not, this will perhaps now be `None`
* I am quite sure that it will not remove the myMesh key from the myMesh.tags dictionary.

**Comment by pshriwise** [comment]
This should "just work" with `del myMesh.tag`, yes. Because it is called as an attribute of a class, it is cleaned up on the Python class as well. And because `tag_delete` is called in the `__delete__` method of the `NativeMeshTag` class, it should be removed automatically from the PyMOAB instance as well. (the other `pyne.mesh.Tag` types have their own `__delete__` methods).

**Comment by gonuke** [comment]
It looks like that by deleting both the attr and the entry in the dictionary, the Tag object will then be deleted

**Comment by gonuke** [comment]
Maybe we need to add `del mesh.tags[tag_name]` to the `Tag.__delete__()` method?

**Comment by pshriwise** [comment]
Oh yeah, that should be done there too probably.

**Comment by pshriwise** [comment]
Oh yeah, that should be done there too probably.

**Comment by pshriwise** [comment]
Something seems wrong though. The infrastructure is there... but I'm having trouble getting the expected behavior...

**Comment by gonuke** [comment]
That doesn't quite do it.... and we are at the boundary of my python knowledge :)

Once a tag is created, there are two references to the `Tag` object: the Mesh object attribute `myMesh.myTag` and the entry in the Mesh object's `tags` dictionary.

Deleting either one of those does not fully remove the references to the object.  Both need to be deleted for all the reference count to go to 0 and then remove the object.

**Comment by pshriwise** [comment]
And neither of those will remove it from the PyMOAB instance unless `det myTag` is called...there's more doing on here than I initially thought. This piece complicates things. I think what we may want is to provide a custom `__del__` method on the Tag classes. This will allow us to remove the tag from the PyMOAB instance during garbage collection.

**Comment by gonuke** [comment]
I was just going to make a `delete_tag` method on `Mesh` that called `del` on both the `attr` and the dictionary entry (at least for now)

**Comment by pshriwise** [comment]
I think that's a good call.

SMH I don't think that the `__delete__` methods are going to cut it for this design. After some reading (and frustration trying to get PyNE to access those methods automatically) I learned something today. Those methods will be called *only* if the class attribute is *not* dynamic. (i.e. the attribute is not created as `self.attr = val` but rather is always part of the class)

**Comment by pshriwise** [comment]
Because I found this interesting I'll throw a test code snippet up as an example: 

```
class Bar(object):
    def __init__(self):
        self.value = ''
    def __get__(self, instance, owner):
        print "returned from descriptor object"
        return self.value
    def __set__(self, instance, value):
        print "set in descriptor object"
        self.value = value
    def __delete__(self, instance):
        print "deleted in descriptor object"
        del self.value

class Foo(object):
    bar = Bar()

class Boo(object):

    def __init__(self):
        self.bar = ''


print("Foo Example:")
f = Foo()
f.bar = 10
print f.bar
del f.bar # accesses Bar's __delete__ method

print

print("Boo Example:")
b = Boo()
b.bar = 10
print b.bar
del b.bar # does not access Bar's __delete__ method
```
