### ISSUE TITLE
document the most likely changes that PyNE users may need to make to accommodate the new PyNE Mesh class

### ISSUE THREAD

**Issue by gonuke** [cnerg/pyne#27]
There are a few key differences between the API for the previous PyNE Mesh class and the new PyMOAB based one.  E.g. myMesh.mesh.save() vs myMesh.save()

These should be documented somewhere to help other users transition their code that may depend on PyNE.  This probably warrants a new page specific to this mesh API transition.

**Comment by pshriwise** [comment]
I haven't looked at the current work on this (so this may be there already), but we should make sure to include an example of tagging a mesh instance with information. 

tag[mesh.mesh.getRootSet()] = val :arrow_right:  tag[mesh] = val

I'm now noting that this may only work for the `NativeMeshTag` class.

**Comment by gonuke** [comment]
This last comments was incorporated into the review of the main PR by @gonuke
