### ISSUE TITLE
A call to Mesh should either succeed or fail more gracefully.

### ISSUE THREAD

**Issue by pshriwise** [cnerg/pyne#30]
As it stands, the line `m = pyne.mesh.Mesh()` will fail when it cannot find any volume elements to check for tags in the mesh module. 

This kind of mesh creation should either succeed - though I'm not sure what use that is or what it would look like - or it should fail with some kind of exception/message with information on how to create a PyNE mesh properly.

IMO the latter is a better choice for now.

**Comment by pshriwise** [comment]
I'll note that this is a pre-existing behavior of PyNE, so it could also have been added to the PyNE repo there, but I figure while we're at it....

**Comment by gonuke** [comment]
Which line is this?  line 829?  are we sure that the failing test is actually a necessary part of Mesh initialization?  Does the whole process of Mesh initialization need to be reviewed?

**Comment by gonuke** [comment]
Since this would (probably) fail in the old implementation, we'll punt this back to pyne/pyne.

**Comment by pshriwise** [comment]
I can confirm that this will fail in the old implementation as well. Thanks for following up on it!
