### ISSUE TITLE
Add CI for r2s script (?)

### ISSUE THREAD

**Issue by gonuke** [cnerg/pyne#34]
Consider how best to test the R2S script as part of CI without actually running MCNP or ALARA.  (and if it is worth it)

**Comment by zxkjack123** [comment]
Files prepared for CI:
 - Input and output files for neutron transport. Including "geom.h5m", "input", "output", "meshtal"
 - Modified ALARA input files:
      - data: nuclear data
      - config.ini: modified version. parameter grid set to be True to avoid randomness in ray tracing
      - alara_params.txt: modified version for test
- Expected output files of 'r2s.py  step1':
      - exp_alara_inp
      - exp_alara_fluxin
      - exp_alara_matlib
- Output of ALARA calculation (also the input of the 'r2s.py step2'):
      - output.txt
      - phtn_src
- Expected output files of 'r2s.py step2':
      - exp_e_bounds
      - exp_total_photon_source_intensities.txt

**Comment by zxkjack123** [comment]
The input files for the 'r2s.py' step1 is prepared. The output files of 'r2s.py step1' and the output files of ALARA compose the input files for 'r2s.py step2'.

The output files of step1 and step2 in text format (exp_*) will be compared (using a check_r2s.py script) after the 'r2s.py step2'. Therefore, the CI command should include the following three lines:
- run 'r2s.py step1'
- run 'r2s.py step2'
- run 'python check_r2s.py'

The script 'check_r2s.py' may need modification to pass the check result to CI.

**Comment by zxkjack123** [comment]
Done in https://github.com/pyne/pyne/pull/1114.
