### ISSUE TITLE
Update R2S example to include output files from MCNP and ALARA

### ISSUE THREAD

**Issue by gonuke** [cnerg/pyne#4]
The R2S example that is described in the documents includes a link to a tarball with all the files necessary for a "student" to run an R2S problem.

A correct set of output files should also be added so that:
1. we can test the R2S script in CI without running physics codes
2. "students" can compare their answers

**Comment by zxkjack123** [comment]
The current R2S example is designed for voxel R2S only. The example files and documentations should be updated as the subvoxel R2S is available now.

**Comment by zxkjack123** [comment]
The input/ouput files of voxel R2S and subvoxel are generally similar in formats and names. But their contents are different. This could lead to confusion. To make it more clear, I will put them into two separate tarballs such as `voxel_r2s_example.tar.gz` and `subvoxel_r2s_examplel.tar.gz`, and mention their difference and usage in the documentation.

But there is a question I need your suggestion @gonuke . Should I use the same geometry for both voxel and subvoxel R2S examples?

**Comment by zxkjack123** [comment]
The input/output files for the first step of R2S (neutron transport) is exactly the same. So, it's better to share the files of neutron transport. And then add both files for `r2s` and `subvoxel r2s`. Therefore, I decide to use the same geometry for both r2s and subvoxel files.

As if we want to test  R2S (scripts/r2s.py) using a real geometry problem via CI, we need to put the related files into the 'pyne/tests/files_test_r2s'.

Files need for the example:
 - [x] Neutron transport input/output
 - [x] r2s input/output
 - [x] subvoxel r2s input/output
 - [x] 2D-slice of the geometry
 - [x] update description of the content in the userguide
 - [x] 3D view of the geometry (exported from trelis)
 - [x] script to compare the output files (currently works for only text files)
 - [ ] test using CI

**Comment by zxkjack123** [comment]
The output files of r2s step1 are slightly different every time. Becasue the ray tracing's randomness, the cell_fracs for each voxel is slightly different.

For example, the attached two files are the alara_inp from the same input files:


[alara_inp.txt](https://github.com/CNERG/pyne/files/2737823/alara_inp.txt)
[exp_alara_inp.txt](https://github.com/CNERG/pyne/files/2737824/exp_alara_inp.txt)

**Comment by zxkjack123** [comment]
Updated files are stored here: https://github.com/pyne/data/pull/17. 
- Changed the grid option in the `config.ini` to `True` to avoid the randomness during the ray tracing for this test geometry.
- Add a script `check_r2s.py` to compare the output files (txt files)

**Comment by zxkjack123** [comment]
The content in this issue is independent of the pymoab. So, the PR is presented directly on pyne/pyne here:  https://github.com/pyne/pyne/pull/1085

**Comment by gonuke** [comment]
Thanks @zxkjack123 - I think it's OK to leave the CI additions to another issue/PR
